//
//  CountriesData.swift
//  CapitalsQuiz
//
//  Created on 12/25/25.
//

import Foundation

struct CountriesData {
    static let allCountries: [Country] = [
        // Africa
        Country(name: "Algeria", capital: "Algiers", continent: .africa),
        Country(name: "Angola", capital: "Luanda", continent: .africa),
        Country(name: "Benin", capital: "Porto-Novo", continent: .africa),
        Country(name: "Botswana", capital: "Gaborone", continent: .africa),
        Country(name: "Burkina Faso", capital: "Ouagadougou", continent: .africa),
        Country(name: "Burundi", capital: "Gitega", continent: .africa),
        Country(name: "Cameroon", capital: "Yaoundé", continent: .africa),
        Country(name: "Cape Verde", capital: "Praia", continent: .africa),
        Country(name: "Central African Republic", capital: "Bangui", continent: .africa),
        Country(name: "Chad", capital: "N'Djamena", continent: .africa),
        Country(name: "Comoros", capital: "Moroni", continent: .africa),
        Country(name: "Congo", capital: "Brazzaville", continent: .africa),
        Country(name: "Democratic Republic of the Congo", capital: "Kinshasa", continent: .africa),
        Country(name: "Djibouti", capital: "Djibouti", continent: .africa),
        Country(name: "Egypt", capital: "Cairo", continent: .africa),
        Country(name: "Equatorial Guinea", capital: "Malabo", continent: .africa),
        Country(name: "Eritrea", capital: "Asmara", continent: .africa),
        Country(name: "Eswatini", capital: "Mbabane", continent: .africa),
        Country(name: "Ethiopia", capital: "Addis Ababa", continent: .africa),
        Country(name: "Gabon", capital: "Libreville", continent: .africa),
        Country(name: "Gambia", capital: "Banjul", continent: .africa),
        Country(name: "Ghana", capital: "Accra", continent: .africa),
        Country(name: "Guinea", capital: "Conakry", continent: .africa),
        Country(name: "Guinea-Bissau", capital: "Bissau", continent: .africa),
        Country(name: "Ivory Coast", capital: "Yamoussoukro", continent: .africa),
        Country(name: "Kenya", capital: "Nairobi", continent: .africa),
        Country(name: "Lesotho", capital: "Maseru", continent: .africa),
        Country(name: "Liberia", capital: "Monrovia", continent: .africa),
        Country(name: "Libya", capital: "Tripoli", continent: .africa),
        Country(name: "Madagascar", capital: "Antananarivo", continent: .africa),
        Country(name: "Malawi", capital: "Lilongwe", continent: .africa),
        Country(name: "Mali", capital: "Bamako", continent: .africa),
        Country(name: "Mauritania", capital: "Nouakchott", continent: .africa),
        Country(name: "Mauritius", capital: "Port Louis", continent: .africa),
        Country(name: "Morocco", capital: "Rabat", continent: .africa),
        Country(name: "Mozambique", capital: "Maputo", continent: .africa),
        Country(name: "Namibia", capital: "Windhoek", continent: .africa),
        Country(name: "Niger", capital: "Niamey", continent: .africa),
        Country(name: "Nigeria", capital: "Abuja", continent: .africa),
        Country(name: "Rwanda", capital: "Kigali", continent: .africa),
        Country(name: "São Tomé and Príncipe", capital: "São Tomé", continent: .africa),
        Country(name: "Senegal", capital: "Dakar", continent: .africa),
        Country(name: "Seychelles", capital: "Victoria", continent: .africa),
        Country(name: "Sierra Leone", capital: "Freetown", continent: .africa),
        Country(name: "Somalia", capital: "Mogadishu", continent: .africa),
        Country(name: "South Africa", capital: "Pretoria", continent: .africa),
        Country(name: "South Sudan", capital: "Juba", continent: .africa),
        Country(name: "Sudan", capital: "Khartoum", continent: .africa),
        Country(name: "Tanzania", capital: "Dodoma", continent: .africa),
        Country(name: "Togo", capital: "Lomé", continent: .africa),
        Country(name: "Tunisia", capital: "Tunis", continent: .africa),
        Country(name: "Uganda", capital: "Kampala", continent: .africa),
        Country(name: "Zambia", capital: "Lusaka", continent: .africa),
        Country(name: "Zimbabwe", capital: "Harare", continent: .africa),
        
        // Asia
        Country(name: "Afghanistan", capital: "Kabul", continent: .asia),
        Country(name: "Armenia", capital: "Yerevan", continent: .asia),
        Country(name: "Azerbaijan", capital: "Baku", continent: .asia),
        Country(name: "Bahrain", capital: "Manama", continent: .asia),
        Country(name: "Bangladesh", capital: "Dhaka", continent: .asia),
        Country(name: "Bhutan", capital: "Thimphu", continent: .asia),
        Country(name: "Brunei", capital: "Bandar Seri Begawan", continent: .asia),
        Country(name: "Cambodia", capital: "Phnom Penh", continent: .asia),
        Country(name: "China", capital: "Beijing", continent: .asia),
        Country(name: "Cyprus", capital: "Nicosia", continent: .asia),
        Country(name: "Georgia", capital: "Tbilisi", continent: .asia),
        Country(name: "India", capital: "New Delhi", continent: .asia),
        Country(name: "Indonesia", capital: "Jakarta", continent: .asia),
        Country(name: "Iran", capital: "Tehran", continent: .asia),
        Country(name: "Iraq", capital: "Baghdad", continent: .asia),
        Country(name: "Israel", capital: "Jerusalem", continent: .asia),
        Country(name: "Japan", capital: "Tokyo", continent: .asia),
        Country(name: "Jordan", capital: "Amman", continent: .asia),
        Country(name: "Kazakhstan", capital: "Astana", continent: .asia),
        Country(name: "Kuwait", capital: "Kuwait City", continent: .asia),
        Country(name: "Kyrgyzstan", capital: "Bishkek", continent: .asia),
        Country(name: "Laos", capital: "Vientiane", continent: .asia),
        Country(name: "Lebanon", capital: "Beirut", continent: .asia),
        Country(name: "Malaysia", capital: "Kuala Lumpur", continent: .asia),
        Country(name: "Maldives", capital: "Malé", continent: .asia),
        Country(name: "Mongolia", capital: "Ulaanbaatar", continent: .asia),
        Country(name: "Myanmar", capital: "Naypyidaw", continent: .asia),
        Country(name: "Nepal", capital: "Kathmandu", continent: .asia),
        Country(name: "North Korea", capital: "Pyongyang", continent: .asia),
        Country(name: "Oman", capital: "Muscat", continent: .asia),
        Country(name: "Pakistan", capital: "Islamabad", continent: .asia),
        Country(name: "Palestine", capital: "Ramallah", continent: .asia),
        Country(name: "Philippines", capital: "Manila", continent: .asia),
        Country(name: "Qatar", capital: "Doha", continent: .asia),
        Country(name: "Saudi Arabia", capital: "Riyadh", continent: .asia),
        Country(name: "Singapore", capital: "Singapore", continent: .asia),
        Country(name: "South Korea", capital: "Seoul", continent: .asia),
        Country(name: "Sri Lanka", capital: "Sri Jayawardenepura Kotte", continent: .asia),
        Country(name: "Syria", capital: "Damascus", continent: .asia),
        Country(name: "Taiwan", capital: "Taipei", continent: .asia),
        Country(name: "Tajikistan", capital: "Dushanbe", continent: .asia),
        Country(name: "Thailand", capital: "Bangkok", continent: .asia),
        Country(name: "Timor-Leste", capital: "Dili", continent: .asia),
        Country(name: "Turkey", capital: "Ankara", continent: .asia),
        Country(name: "Turkmenistan", capital: "Ashgabat", continent: .asia),
        Country(name: "United Arab Emirates", capital: "Abu Dhabi", continent: .asia),
        Country(name: "Uzbekistan", capital: "Tashkent", continent: .asia),
        Country(name: "Vietnam", capital: "Hanoi", continent: .asia),
        Country(name: "Yemen", capital: "Sana'a", continent: .asia),
        
        // Europe
        Country(name: "Albania", capital: "Tirana", continent: .europe),
        Country(name: "Andorra", capital: "Andorra la Vella", continent: .europe),
        Country(name: "Austria", capital: "Vienna", continent: .europe),
        Country(name: "Belarus", capital: "Minsk", continent: .europe),
        Country(name: "Belgium", capital: "Brussels", continent: .europe),
        Country(name: "Bosnia and Herzegovina", capital: "Sarajevo", continent: .europe),
        Country(name: "Bulgaria", capital: "Sofia", continent: .europe),
        Country(name: "Croatia", capital: "Zagreb", continent: .europe),
        Country(name: "Czech Republic", capital: "Prague", continent: .europe),
        Country(name: "Denmark", capital: "Copenhagen", continent: .europe),
        Country(name: "Estonia", capital: "Tallinn", continent: .europe),
        Country(name: "Finland", capital: "Helsinki", continent: .europe),
        Country(name: "France", capital: "Paris", continent: .europe),
        Country(name: "Germany", capital: "Berlin", continent: .europe),
        Country(name: "Greece", capital: "Athens", continent: .europe),
        Country(name: "Hungary", capital: "Budapest", continent: .europe),
        Country(name: "Iceland", capital: "Reykjavik", continent: .europe),
        Country(name: "Ireland", capital: "Dublin", continent: .europe),
        Country(name: "Italy", capital: "Rome", continent: .europe),
        Country(name: "Kosovo", capital: "Pristina", continent: .europe),
        Country(name: "Latvia", capital: "Riga", continent: .europe),
        Country(name: "Liechtenstein", capital: "Vaduz", continent: .europe),
        Country(name: "Lithuania", capital: "Vilnius", continent: .europe),
        Country(name: "Luxembourg", capital: "Luxembourg", continent: .europe),
        Country(name: "Malta", capital: "Valletta", continent: .europe),
        Country(name: "Moldova", capital: "Chișinău", continent: .europe),
        Country(name: "Monaco", capital: "Monaco", continent: .europe),
        Country(name: "Montenegro", capital: "Podgorica", continent: .europe),
        Country(name: "Netherlands", capital: "Amsterdam", continent: .europe),
        Country(name: "North Macedonia", capital: "Skopje", continent: .europe),
        Country(name: "Norway", capital: "Oslo", continent: .europe),
        Country(name: "Poland", capital: "Warsaw", continent: .europe),
        Country(name: "Portugal", capital: "Lisbon", continent: .europe),
        Country(name: "Romania", capital: "Bucharest", continent: .europe),
        Country(name: "Russia", capital: "Moscow", continent: .europe),
        Country(name: "San Marino", capital: "San Marino", continent: .europe),
        Country(name: "Serbia", capital: "Belgrade", continent: .europe),
        Country(name: "Slovakia", capital: "Bratislava", continent: .europe),
        Country(name: "Slovenia", capital: "Ljubljana", continent: .europe),
        Country(name: "Spain", capital: "Madrid", continent: .europe),
        Country(name: "Sweden", capital: "Stockholm", continent: .europe),
        Country(name: "Switzerland", capital: "Bern", continent: .europe),
        Country(name: "Ukraine", capital: "Kyiv", continent: .europe),
        Country(name: "United Kingdom", capital: "London", continent: .europe),
        Country(name: "Vatican City", capital: "Vatican City", continent: .europe),
        
        // North America
        Country(name: "Antigua and Barbuda", capital: "St. John's", continent: .northAmerica),
        Country(name: "Bahamas", capital: "Nassau", continent: .northAmerica),
        Country(name: "Barbados", capital: "Bridgetown", continent: .northAmerica),
        Country(name: "Belize", capital: "Belmopan", continent: .northAmerica),
        Country(name: "Canada", capital: "Ottawa", continent: .northAmerica),
        Country(name: "Costa Rica", capital: "San José", continent: .northAmerica),
        Country(name: "Cuba", capital: "Havana", continent: .northAmerica),
        Country(name: "Dominica", capital: "Roseau", continent: .northAmerica),
        Country(name: "Dominican Republic", capital: "Santo Domingo", continent: .northAmerica),
        Country(name: "El Salvador", capital: "San Salvador", continent: .northAmerica),
        Country(name: "Grenada", capital: "St. George's", continent: .northAmerica),
        Country(name: "Guatemala", capital: "Guatemala City", continent: .northAmerica),
        Country(name: "Haiti", capital: "Port-au-Prince", continent: .northAmerica),
        Country(name: "Honduras", capital: "Tegucigalpa", continent: .northAmerica),
        Country(name: "Jamaica", capital: "Kingston", continent: .northAmerica),
        Country(name: "Mexico", capital: "Mexico City", continent: .northAmerica),
        Country(name: "Nicaragua", capital: "Managua", continent: .northAmerica),
        Country(name: "Panama", capital: "Panama City", continent: .northAmerica),
        Country(name: "Saint Kitts and Nevis", capital: "Basseterre", continent: .northAmerica),
        Country(name: "Saint Lucia", capital: "Castries", continent: .northAmerica),
        Country(name: "Saint Vincent and the Grenadines", capital: "Kingstown", continent: .northAmerica),
        Country(name: "Trinidad and Tobago", capital: "Port of Spain", continent: .northAmerica),
        Country(name: "United States", capital: "Washington, D.C.", continent: .northAmerica),
        
        // South America
        Country(name: "Argentina", capital: "Buenos Aires", continent: .southAmerica),
        Country(name: "Bolivia", capital: "La Paz", continent: .southAmerica),
        Country(name: "Brazil", capital: "Brasília", continent: .southAmerica),
        Country(name: "Chile", capital: "Santiago", continent: .southAmerica),
        Country(name: "Colombia", capital: "Bogotá", continent: .southAmerica),
        Country(name: "Ecuador", capital: "Quito", continent: .southAmerica),
        Country(name: "Guyana", capital: "Georgetown", continent: .southAmerica),
        Country(name: "Paraguay", capital: "Asunción", continent: .southAmerica),
        Country(name: "Peru", capital: "Lima", continent: .southAmerica),
        Country(name: "Suriname", capital: "Paramaribo", continent: .southAmerica),
        Country(name: "Uruguay", capital: "Montevideo", continent: .southAmerica),
        Country(name: "Venezuela", capital: "Caracas", continent: .southAmerica),
        
        // Oceania
        Country(name: "Australia", capital: "Canberra", continent: .oceania),
        Country(name: "Fiji", capital: "Suva", continent: .oceania),
        Country(name: "Kiribati", capital: "Tarawa", continent: .oceania),
        Country(name: "Marshall Islands", capital: "Majuro", continent: .oceania),
        Country(name: "Micronesia", capital: "Palikir", continent: .oceania),
        Country(name: "Nauru", capital: "Yaren", continent: .oceania),
        Country(name: "New Zealand", capital: "Wellington", continent: .oceania),
        Country(name: "Palau", capital: "Ngerulmud", continent: .oceania),
        Country(name: "Papua New Guinea", capital: "Port Moresby", continent: .oceania),
        Country(name: "Samoa", capital: "Apia", continent: .oceania),
        Country(name: "Solomon Islands", capital: "Honiara", continent: .oceania),
        Country(name: "Tonga", capital: "Nuku'alofa", continent: .oceania),
        Country(name: "Tuvalu", capital: "Funafuti", continent: .oceania),
        Country(name: "Vanuatu", capital: "Port Vila", continent: .oceania)
    ]
}
