//
//  CountriesData.swift
//  CapitalsQuiz
//
//  Created on 12/25/25.
//

import Foundation

struct CountriesData {
    static let allCountries: [Country] = [
        // Africa
        Country(name: "Algeria", capital: "Algiers"),
        Country(name: "Angola", capital: "Luanda"),
        Country(name: "Benin", capital: "Porto-Novo"),
        Country(name: "Botswana", capital: "Gaborone"),
        Country(name: "Burkina Faso", capital: "Ouagadougou"),
        Country(name: "Burundi", capital: "Gitega"),
        Country(name: "Cameroon", capital: "Yaoundé"),
        Country(name: "Cape Verde", capital: "Praia"),
        Country(name: "Central African Republic", capital: "Bangui"),
        Country(name: "Chad", capital: "N'Djamena"),
        Country(name: "Comoros", capital: "Moroni"),
        Country(name: "Congo", capital: "Brazzaville"),
        Country(name: "Democratic Republic of the Congo", capital: "Kinshasa"),
        Country(name: "Djibouti", capital: "Djibouti"),
        Country(name: "Egypt", capital: "Cairo"),
        Country(name: "Equatorial Guinea", capital: "Malabo"),
        Country(name: "Eritrea", capital: "Asmara"),
        Country(name: "Eswatini", capital: "Mbabane"),
        Country(name: "Ethiopia", capital: "Addis Ababa"),
        Country(name: "Gabon", capital: "Libreville"),
        Country(name: "Gambia", capital: "Banjul"),
        Country(name: "Ghana", capital: "Accra"),
        Country(name: "Guinea", capital: "Conakry"),
        Country(name: "Guinea-Bissau", capital: "Bissau"),
        Country(name: "Ivory Coast", capital: "Yamoussoukro"),
        Country(name: "Kenya", capital: "Nairobi"),
        Country(name: "Lesotho", capital: "Maseru"),
        Country(name: "Liberia", capital: "Monrovia"),
        Country(name: "Libya", capital: "Tripoli"),
        Country(name: "Madagascar", capital: "Antananarivo"),
        Country(name: "Malawi", capital: "Lilongwe"),
        Country(name: "Mali", capital: "Bamako"),
        Country(name: "Mauritania", capital: "Nouakchott"),
        Country(name: "Mauritius", capital: "Port Louis"),
        Country(name: "Morocco", capital: "Rabat"),
        Country(name: "Mozambique", capital: "Maputo"),
        Country(name: "Namibia", capital: "Windhoek"),
        Country(name: "Niger", capital: "Niamey"),
        Country(name: "Nigeria", capital: "Abuja"),
        Country(name: "Rwanda", capital: "Kigali"),
        Country(name: "São Tomé and Príncipe", capital: "São Tomé"),
        Country(name: "Senegal", capital: "Dakar"),
        Country(name: "Seychelles", capital: "Victoria"),
        Country(name: "Sierra Leone", capital: "Freetown"),
        Country(name: "Somalia", capital: "Mogadishu"),
        Country(name: "South Africa", capital: "Pretoria"),
        Country(name: "South Sudan", capital: "Juba"),
        Country(name: "Sudan", capital: "Khartoum"),
        Country(name: "Tanzania", capital: "Dodoma"),
        Country(name: "Togo", capital: "Lomé"),
        Country(name: "Tunisia", capital: "Tunis"),
        Country(name: "Uganda", capital: "Kampala"),
        Country(name: "Zambia", capital: "Lusaka"),
        Country(name: "Zimbabwe", capital: "Harare"),
        
        // Asia
        Country(name: "Afghanistan", capital: "Kabul"),
        Country(name: "Armenia", capital: "Yerevan"),
        Country(name: "Azerbaijan", capital: "Baku"),
        Country(name: "Bahrain", capital: "Manama"),
        Country(name: "Bangladesh", capital: "Dhaka"),
        Country(name: "Bhutan", capital: "Thimphu"),
        Country(name: "Brunei", capital: "Bandar Seri Begawan"),
        Country(name: "Cambodia", capital: "Phnom Penh"),
        Country(name: "China", capital: "Beijing"),
        Country(name: "Cyprus", capital: "Nicosia"),
        Country(name: "Georgia", capital: "Tbilisi"),
        Country(name: "India", capital: "New Delhi"),
        Country(name: "Indonesia", capital: "Jakarta"),
        Country(name: "Iran", capital: "Tehran"),
        Country(name: "Iraq", capital: "Baghdad"),
        Country(name: "Israel", capital: "Jerusalem"),
        Country(name: "Japan", capital: "Tokyo"),
        Country(name: "Jordan", capital: "Amman"),
        Country(name: "Kazakhstan", capital: "Astana"),
        Country(name: "Kuwait", capital: "Kuwait City"),
        Country(name: "Kyrgyzstan", capital: "Bishkek"),
        Country(name: "Laos", capital: "Vientiane"),
        Country(name: "Lebanon", capital: "Beirut"),
        Country(name: "Malaysia", capital: "Kuala Lumpur"),
        Country(name: "Maldives", capital: "Malé"),
        Country(name: "Mongolia", capital: "Ulaanbaatar"),
        Country(name: "Myanmar", capital: "Naypyidaw"),
        Country(name: "Nepal", capital: "Kathmandu"),
        Country(name: "North Korea", capital: "Pyongyang"),
        Country(name: "Oman", capital: "Muscat"),
        Country(name: "Pakistan", capital: "Islamabad"),
        Country(name: "Palestine", capital: "Ramallah"),
        Country(name: "Philippines", capital: "Manila"),
        Country(name: "Qatar", capital: "Doha"),
        Country(name: "Saudi Arabia", capital: "Riyadh"),
        Country(name: "Singapore", capital: "Singapore"),
        Country(name: "South Korea", capital: "Seoul"),
        Country(name: "Sri Lanka", capital: "Sri Jayawardenepura Kotte"),
        Country(name: "Syria", capital: "Damascus"),
        Country(name: "Taiwan", capital: "Taipei"),
        Country(name: "Tajikistan", capital: "Dushanbe"),
        Country(name: "Thailand", capital: "Bangkok"),
        Country(name: "Timor-Leste", capital: "Dili"),
        Country(name: "Turkey", capital: "Ankara"),
        Country(name: "Turkmenistan", capital: "Ashgabat"),
        Country(name: "United Arab Emirates", capital: "Abu Dhabi"),
        Country(name: "Uzbekistan", capital: "Tashkent"),
        Country(name: "Vietnam", capital: "Hanoi"),
        Country(name: "Yemen", capital: "Sana'a"),
        
        // Europe
        Country(name: "Albania", capital: "Tirana"),
        Country(name: "Andorra", capital: "Andorra la Vella"),
        Country(name: "Austria", capital: "Vienna"),
        Country(name: "Belarus", capital: "Minsk"),
        Country(name: "Belgium", capital: "Brussels"),
        Country(name: "Bosnia and Herzegovina", capital: "Sarajevo"),
        Country(name: "Bulgaria", capital: "Sofia"),
        Country(name: "Croatia", capital: "Zagreb"),
        Country(name: "Czech Republic", capital: "Prague"),
        Country(name: "Denmark", capital: "Copenhagen"),
        Country(name: "Estonia", capital: "Tallinn"),
        Country(name: "Finland", capital: "Helsinki"),
        Country(name: "France", capital: "Paris"),
        Country(name: "Germany", capital: "Berlin"),
        Country(name: "Greece", capital: "Athens"),
        Country(name: "Hungary", capital: "Budapest"),
        Country(name: "Iceland", capital: "Reykjavik"),
        Country(name: "Ireland", capital: "Dublin"),
        Country(name: "Italy", capital: "Rome"),
        Country(name: "Kosovo", capital: "Pristina"),
        Country(name: "Latvia", capital: "Riga"),
        Country(name: "Liechtenstein", capital: "Vaduz"),
        Country(name: "Lithuania", capital: "Vilnius"),
        Country(name: "Luxembourg", capital: "Luxembourg"),
        Country(name: "Malta", capital: "Valletta"),
        Country(name: "Moldova", capital: "Chișinău"),
        Country(name: "Monaco", capital: "Monaco"),
        Country(name: "Montenegro", capital: "Podgorica"),
        Country(name: "Netherlands", capital: "Amsterdam"),
        Country(name: "North Macedonia", capital: "Skopje"),
        Country(name: "Norway", capital: "Oslo"),
        Country(name: "Poland", capital: "Warsaw"),
        Country(name: "Portugal", capital: "Lisbon"),
        Country(name: "Romania", capital: "Bucharest"),
        Country(name: "Russia", capital: "Moscow"),
        Country(name: "San Marino", capital: "San Marino"),
        Country(name: "Serbia", capital: "Belgrade"),
        Country(name: "Slovakia", capital: "Bratislava"),
        Country(name: "Slovenia", capital: "Ljubljana"),
        Country(name: "Spain", capital: "Madrid"),
        Country(name: "Sweden", capital: "Stockholm"),
        Country(name: "Switzerland", capital: "Bern"),
        Country(name: "Ukraine", capital: "Kyiv"),
        Country(name: "United Kingdom", capital: "London"),
        Country(name: "Vatican City", capital: "Vatican City"),
        
        // North America
        Country(name: "Antigua and Barbuda", capital: "St. John's"),
        Country(name: "Bahamas", capital: "Nassau"),
        Country(name: "Barbados", capital: "Bridgetown"),
        Country(name: "Belize", capital: "Belmopan"),
        Country(name: "Canada", capital: "Ottawa"),
        Country(name: "Costa Rica", capital: "San José"),
        Country(name: "Cuba", capital: "Havana"),
        Country(name: "Dominica", capital: "Roseau"),
        Country(name: "Dominican Republic", capital: "Santo Domingo"),
        Country(name: "El Salvador", capital: "San Salvador"),
        Country(name: "Grenada", capital: "St. George's"),
        Country(name: "Guatemala", capital: "Guatemala City"),
        Country(name: "Haiti", capital: "Port-au-Prince"),
        Country(name: "Honduras", capital: "Tegucigalpa"),
        Country(name: "Jamaica", capital: "Kingston"),
        Country(name: "Mexico", capital: "Mexico City"),
        Country(name: "Nicaragua", capital: "Managua"),
        Country(name: "Panama", capital: "Panama City"),
        Country(name: "Saint Kitts and Nevis", capital: "Basseterre"),
        Country(name: "Saint Lucia", capital: "Castries"),
        Country(name: "Saint Vincent and the Grenadines", capital: "Kingstown"),
        Country(name: "Trinidad and Tobago", capital: "Port of Spain"),
        Country(name: "United States", capital: "Washington, D.C."),
        
        // South America
        Country(name: "Argentina", capital: "Buenos Aires"),
        Country(name: "Bolivia", capital: "La Paz"),
        Country(name: "Brazil", capital: "Brasília"),
        Country(name: "Chile", capital: "Santiago"),
        Country(name: "Colombia", capital: "Bogotá"),
        Country(name: "Ecuador", capital: "Quito"),
        Country(name: "Guyana", capital: "Georgetown"),
        Country(name: "Paraguay", capital: "Asunción"),
        Country(name: "Peru", capital: "Lima"),
        Country(name: "Suriname", capital: "Paramaribo"),
        Country(name: "Uruguay", capital: "Montevideo"),
        Country(name: "Venezuela", capital: "Caracas"),
        
        // Oceania
        Country(name: "Australia", capital: "Canberra"),
        Country(name: "Fiji", capital: "Suva"),
        Country(name: "Kiribati", capital: "Tarawa"),
        Country(name: "Marshall Islands", capital: "Majuro"),
        Country(name: "Micronesia", capital: "Palikir"),
        Country(name: "Nauru", capital: "Yaren"),
        Country(name: "New Zealand", capital: "Wellington"),
        Country(name: "Palau", capital: "Ngerulmud"),
        Country(name: "Papua New Guinea", capital: "Port Moresby"),
        Country(name: "Samoa", capital: "Apia"),
        Country(name: "Solomon Islands", capital: "Honiara"),
        Country(name: "Tonga", capital: "Nuku'alofa"),
        Country(name: "Tuvalu", capital: "Funafuti"),
        Country(name: "Vanuatu", capital: "Port Vila")
    ]
}
